//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingStore.Models.DomainModels.DTO.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ShoppingStoreDBFirstEntities1 : DbContext
    {
        public ShoppingStoreDBFirstEntities1()
            : base("name=ShoppingStoreDBFirstEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<OrderMaster> OrderMasters { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Product> Products { get; set; }
    
        public virtual int usp_DeleteCategory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DeleteCategory");
        }
    
        public virtual int usp_DeleteOrder()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DeleteOrder");
        }
    
        public virtual int usp_DeleteOrderProducts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DeleteOrderProducts");
        }
    
        public virtual int usp_DeletePerson()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DeletePerson");
        }
    
        public virtual int usp_DeleteProduct()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DeleteProduct");
        }
    
        public virtual int usp_InsertCategory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertCategory");
        }
    
        public virtual int usp_InsertOrder()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertOrder");
        }
    
        public virtual int usp_InsertPerson()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertPerson");
        }
    
        public virtual int usp_InsertProduct()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertProduct");
        }
    
        public virtual ObjectResult<usp_SelectCategory_Result> usp_SelectCategory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SelectCategory_Result>("usp_SelectCategory");
        }
    
        public virtual ObjectResult<usp_SelectOrderDetail_Result> usp_SelectOrderDetail()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SelectOrderDetail_Result>("usp_SelectOrderDetail");
        }
    
        public virtual ObjectResult<usp_SelectOrderMaster_Result> usp_SelectOrderMaster()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SelectOrderMaster_Result>("usp_SelectOrderMaster");
        }
    
        public virtual ObjectResult<usp_SelectPerson_Result> usp_SelectPerson()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SelectPerson_Result>("usp_SelectPerson");
        }
    
        public virtual ObjectResult<usp_SelectProduct_Result> usp_SelectProduct()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SelectProduct_Result>("usp_SelectProduct");
        }
    
        public virtual int usp_UpdateCategory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateCategory");
        }
    
        public virtual int usp_UpdateOrder()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateOrder");
        }
    
        public virtual int usp_UpdatePerson()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdatePerson");
        }
    
        public virtual int usp_UpdateProduct()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateProduct");
        }
    }
}
