//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingStore.Models.DomainModels.DTO.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ShoppingStoreDBFirstEntities : DbContext
    {
        public ShoppingStoreDBFirstEntities()
            : base("name=ShoppingStoreDBFirstEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<OrderMaster> OrderMasters { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Product> Products { get; set; }
    
        public virtual int usp_DeletePerson()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DeletePerson");
        }
    
        public virtual int usp_DeleteProduct()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DeleteProduct");
        }
    
        public virtual int usp_InsertPerson()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertPerson");
        }
    
        public virtual int usp_InsertProduct()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertProduct");
        }
    
        public virtual ObjectResult<string> usp_SelectCategory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_SelectCategory");
        }
    
        public virtual ObjectResult<usp_SelectPerson_Result> usp_SelectPerson()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SelectPerson_Result>("usp_SelectPerson");
        }
    
        public virtual ObjectResult<usp_SelectProduct_Result> usp_SelectProduct()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SelectProduct_Result>("usp_SelectProduct");
        }
    
        public virtual int usp_UpdatePerson()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdatePerson");
        }
    
        public virtual int usp_UpdateProduct()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateProduct");
        }
    }
}
